apiVersion: v1
kind: ConfigMap
metadata:
  name: my-api-config
  labels:
    app: my-api
data:
  log-level: info
  node-env: production
  postgres-host: postgres
  postgres-port: '5432'
  postgres-database: myapp
  postgres-user: postgres
  redis-host: redis
  redis-port: '6379'
