apiVersion: v1
kind: Secret
metadata:
  name: my-api-secret
  labels:
    app: my-api
type: Opaque
stringData:
  postgres-password: CHANGE_ME_IN_PRODUCTION
  jwt-secret: CHANGE_ME_IN_PRODUCTION_USE_LONG_RANDOM_STRING
